### ISSUE TITLE
[Feature Request] Support better vue-router integration

### ISSUE THREAD

**Issue by h6ah4i** [ktsn/vuex-connect#33]
Hi. Thanks for the useful library!

However, I noticed that the wrapped component that `vuex-connect` generate has some drawbacks when trying to use with `vue-router`. Do you have any plan to improve the integration with `vue-router`?

### 1. In-component guards hooks

These component hooks are used by `vue-router`, but currently no way to declare them.

- beforeRouteEnter
- beforeRouteUpdate
- beforeRouteLeave

https://router.vuejs.org/en/advanced/navigation-guards.html#in-component-guards

### 2. Declaring props for accepting router's parameters

Props are used to pass parameters from 'vue-router`.

**Comment by ktsn** [comment]
Thanks for your suggestion.

> 1. In-component guards hooks

I'll add a new feature to let the users define some custom hooks in the next version.

> 2. Declaring props for accepting router's parameters

Currently, vuex-connect declares props in the wrapper component if you omit connecting state/getters/actions/mutations to them. https://github.com/ktsn/vuex-connect/releases/tag/v0.3.3
Isn't this enough for your usage?

**Comment by h6ah4i** [comment]
Hi. Thanks for your response.

For the second one, I noticed that `vuex-router-sync` is what actually I need. I was trying to refer parameters that is passed from `vue-router` like the following code; the `userId` prop is not required for the inner component but the wrapper component requires it.

```javascript
import UserListContainer from './user-list-container'

const router = new VueRouter({
  routes: [
    {
      path: '/users/:user_id',
      component: UsersListContainer,
      props: (route) => ({ userId: parseInt(route.params.user_id, 10) })
    }
  ]
})

// users-list-component.js
export default {
  props: {
    userId: {           // !!! <-- This property is not required for the inner component, but used in wrapper component
        type: Number,
        required: true,
    },
    user: {
      type: Object,
      required: false
    }
  },
  template: `
  <div v-if="user">
    <p>{{ user.id }}</p>
    <p>{{ user.name }}</p>
  </div>
  `
}

// user-list-container.js
import { connect } from 'vuex-connect'
import UserListComponent from './user-list-component'

export default connect({
  // !!! Initially, I wanted to define the "userId" prop here
  // props: {
  //   userId: {
  //     type: Number,
  //     required: true,
  //  },
  // },

  stateToProps: {
    user: state => state.user
  },

  lifecycle: {
    beforeMount({ state, dispatch, commit }) {
      dispatch('FETCH_USER_DATA', this.userId)    // !!! <-- using "userId" declared in UserListContainer
        .then(user => commit('SET_USER', user));

      // !!! After while, I noticed that I can access userId parameter here through vuex-router-sync like this;
      // const userId = parseInt(state.route.params.user_id, 10);
    }
  }
})(UserListComponent)
```

**Comment by ktsn** [comment]
@h6ah4i 
Maybe, this use case is covered if we can handle `beforeRouteEnter` in wrapper component?

```js
connect({
  lifecycle: {
    beforeRouteEnter (store, to, from, next) {
      store.dispatch('FETCH_USER_DATA', to.params.id)
        .then(user => store.commit('SET_USER', user))
    }
  }
})
```

IMO, it should be avoided to declare a new prop in a wrapper component since it is a little complicated. What do you think?

**Comment by h6ah4i** [comment]
@ktsn Yeah, the syntax looks good and very straightforward 😄  Also, I think adding new props to wrapper component is not required anymore.

**Comment by ktsn** [comment]
@h6ah4i 
Published v1.2.0. It includes a new function `createConnect` that allows you to declare any lifecycle hooks. https://github.com/ktsn/vuex-connect#createconnectfn---connectfunction

**Comment by ktsn** [comment]
BTW, I noticed the example I wrote in the previous comment is wrong. As the `beforeRouteEnter` doesn't have `this`, we need to use the `vm.$store` in the callback function of `next`.

```js
connect({
  lifecycle: {
    beforeRouteEnter (to, from, next) {
      next(vm => {
        const store = vm.$store
        store.dispatch('FETCH_USER_DATA', to.params.id)
          .then(user => store.commit('SET_USER', user))
      })
    }
  }
})
```

**Comment by h6ah4i** [comment]
@ktsn Thanks for the wonderful work! I will check that tomorrow :D
