### ISSUE TITLE
Use with .vue files

### ISSUE THREAD

**Issue by linde12** [ktsn/vuex-connect#34]
Hello!

I'm having problems using this with `.vue` files, is there a way you know of to work around this? What seems to be happening is that vue-loader replaces the render function set by `insertRenderer`.

**Comment by ktsn** [comment]
Can you please provide the example repository that reproduce this problem?
As vuex-connect just returns a wrapped component, I think it just works in `.vue` files.

**Comment by linde12** [comment]
I put up a [repo here](https://github.com/linde12/vuex-connect-example) in which i've reproduced the problem. Just run `npm install` or `yarn` and then `npm run dev`.

vue-loader seems to compile the template, import the javascript module, and then inject the render function into that module(which would be the `connect` HOC in this case)

As you can see in my provided example repo, both components are rendered, but only one gives a popup. And if you look using Vue devtools, you will see that `ConnectMyConnectedComponent` isn't a HOC, it's just a single component.

I think it's a problem with how vue-loader works, really, but i thought maybe vuex-connect had some way to work around it? I've also submitted a [feature request for vue-loader](https://github.com/vuejs/vue-loader/issues/723) but no one has taken a look at it yet.

**Comment by ktsn** [comment]
Well, you seems to be misunderstanding how vue-loader and HoC work. vue-loader injects compiled template into **exported** object. If you want to use template in the `.vue` file, you should export the original object (in your example, you should export `Component` rather than `connect`ed object).
So, you need to separate the original component and the wrapped component in different files.

```vue
<!-- MyComponent.vue -->
<template>
  <div>
    Hello {{name}}!
  </div>
</template>

<script>
export default {
  name: 'my-component',
  props: ['name'],
  created () {
    alert(`[created]: ${this.name}`)
  }
}
</script>
```

```js
// MyConnectedComponent.js
import { connect } from 'vuex-connect'
import MyComponent from './MyComponent.vue'

export default connect({
  stateToProps: {
    name: state => state.name
  }
})('my-connected-component', MyComponent)
```

BTW, I think HoC should not be declared in `.vue` file because it should just connect store and component.

**Comment by linde12** [comment]
No, i'm not misunderstanding, i just explained how it worked? 😕

That's exactly what i'm saying; why should you have to create two files to make one connected component? Look at React where you have "container components" that do both things in one file.

I just think that developers shouldn't have to adjust their javascript code because they're in a `.vue` file. It's misleading. Using higher order functions should always work imo.

Having to use two separate files for our "smart" components is off-putting, because it's extra and unnecessary work.

Anyway, if it's not going to be supported i think it should at least be noted that it won't work in `.vue` files and that you should have to use two separate files or render functions.

Anyway this is probably more of a `vue-loader` issue, but i think it could still be a note so that when people tries to use your library they know they have to use `.js` files when they use connect.

**Comment by ktsn** [comment]
Writing both presentational component and its container component is not so much make sense because the strategy is for separating UI (presentation) and adapter to store (container) to achieve testability and reusability of presentational component.

> it should at least be noted that it won't work in .vue files

vuex-connect is also work in .vue file if you don't write `<template>` block. HoC is just wrap the original component in render function, so it is nullified if you define other template.

**Comment by linde12** [comment]
No, of course, but now you have to  either:
a) write your container component with render functions
b) use one .vue file and one .js file for your container

You can't simply do this:
```
<template>
  <presentational-component :someProp="prop" />
</template>
<script>
export default connect({...})('my-container', {...})
</script>
```
Instead you have to split it or write your own render function in a normal javascript file.

I'm also thinking about different HOCs(that don't necessarily connect to Vuex). Or take `redux-form` for example, where every form should connect to the store via the `reduxForm` HOC. I just see it as a problem in general, coming from React where many plugins are HOCs, that you can't use HOCs in `.vue` files.

But i think it's more of a general problem of `vue-loader` so i should probably wait for a reply there.
