### ISSUE TITLE
Slots not working in wrapped component

### ISSUE THREAD

**Issue by johnfraney** [ktsn/vuex-connect#39]
When specifying slots (named or unnamed) in a vuex-connect component, the slot values aren't being applied.

When importing the base component, the page shows the custom slot content as you'd expect. When importing the wrapped component, the default slot content appears.

I've got a minimal demonstration of this [here](https://github.com/johnfraney/vuex-connect-slot-example). The slot content is being customized in `App.vue`.

**Comment by ktsn** [comment]
@johnfraney Thanks. This has been released as v1.3.1

**Comment by johnfraney** [comment]
Nice! Thanks for digging into that. (I probably should've mentioned that I was using the latest version of VueJS.) This is a really useful little plugin. Thanks for sharing it.
