### ISSUE TITLE
Connected component is no able to use events

### ISSUE THREAD

**Issue by MatteoGabriele** [ktsn/vuex-connect#42]
The component we are connecting to the Vuex store, because it's wrapped with the `vuex-connect`, is not able to communicate with its parent via events.

As described in this section of the [documentation](https://vuejs.org/v2/api/#vm-listeners), could be possible to just pass all listeners down using `v-on="$listeners"`

Thanks for your time

**Comment by ktsn** [comment]
Implemented in v2.0.0

**Comment by MatteoGabriele** [comment]
@ktsn Thanks a lot :)
