### ISSUE TITLE
Wrapper Mixins / Keeping Wrappers DRY

### ISSUE THREAD

**Issue by Gregoyle** [ktsn/vuex-connect#43]
Hi there,

I have a lot of wrappers which will need the same set of connect mappings. I'm wondering if the library provides a way to keep this DRY or if I should just store the mappings in a const somewhere and import it whenever I need the set of wrapper mappings that go together? I'm wondering if maybe there is some kind of mixin or something I can leverage in the wrappers.

Thanks for the great library and any guidance is appreciated.

**Comment by ktsn** [comment]
As `connect` is partially curried, you can reuse it out of the box.

```js
const mapper = connect(/* ... */)

const ConnectedA = mapper(ComponentA)
const ConnectedB = mapper(ComponentB)
```

**Comment by AlexandreBonaventure** [comment]
This is great but it doesn't allow composition(via mixins) out the box, doesn't it ?
Would be great to be able to compose features (vuex state + actions) with mixins. Do you have any guidelines for this ?
Thanks
