### ISSUE TITLE
Component instance during connection

### ISSUE THREAD

**Issue by MatteoGabriele** [ktsn/vuex-connect#46]
Currently `this` refers to the component that we are connecting, not the actual component that is hosting it.

example:

```js
import { connect } from 'vuex-connect'
import Foo from '@/components/Foo'

export default {
  name: 'Bar',

  props: {
    id: {
      type: Number,
      required: true
    }
  },

  components: {
    Foo: connect({
      methodsToEvents: {
        save ({ dispatch }, values) {
          dispatch('saveUserData', {
            data: values,
            id: this.id // This is not possible
          })
        }
      }
    })('foo', Foo)
  }
}
```

Would make sense to be able to pass data from the component instance inside the `connect` method.

In this example we can't pass the `id` property of the current component because the context refers to the actual `Foo` component

Thanks for your time

Cheers

**Comment by ktsn** [comment]
This is expected since connect does not try to connect `Bar` but `Foo`... This is the same scenario you cannot access a parent instance from children `this`.

**Comment by MatteoGabriele** [comment]
Got it.
Thanks
