### ISSUE TITLE
Support for Vuex 3.0.0

### ISSUE THREAD

**Issue by mrkirchner** [ktsn/vuex-connect#47]
Seems to be working fine except for a warning:

>  WARN vuex-connect@2.0.1 requires a peer of vuex@^2.0.0-rc but none is installed. You must install peer dependencies yourself.

Can we update the peer dependency to 

'>= 2.0.0'

You would know better if there are any issues with doing that.

Thanks

**Comment by ktsn** [comment]
Fixed in v2.0.3.
