### ISSUE TITLE
named slot content gets put into default slot

### ISSUE THREAD

**Issue by devinholloway** [ktsn/vuex-connect#49]
Given a component such as:
TestComponent.vue
`<template>
    <ul>
      <li><slot>Default Slot</slot></li>
      <li><slot name="test">Test Slot</slot></li>
    </ul>
</template>`

And using the component:
App.vue
`<test-component>
  <span>This should go in default slot</span>
  <span slot="test">This should go in test slot</span>
</test-component>`

If I give TestComponent a connector, all slotted elements (whether they specify a slot name or not) get pushed into the default slot. If I remove the connector, it works properly.

I have a small reproduce-able app here
https://github.com/devinholloway/named-slot-passthrough-connector

**Comment by ktsn** [comment]
Thanks for reporting this. This should be fixed in v2.1.0
