### ISSUE TITLE
Using a custom v-model prop does not get populated

### ISSUE THREAD

**Issue by devinholloway** [ktsn/vuex-connect#51]
This is in reference to this Vue update: https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model

When using a connector, if I, for example, specify a model definition of:

model: {
   prop: 'customProp'
}

the 'customProp' prop will not get populated by v-model. The 'value' prop will continue to be populated.

**Comment by ktsn** [comment]
It's not supported. Please just use prop and event separately.
